# Generated by Django 5.0.14 on 2025-09-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('fecha_estreno', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
